---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-consumer
        v: v11111
    spec:
      hostAliases:
        - ip: "10.106.24.250"
          hostnames:
            - "kafka-service"
      containers:
        - name: consumer
          envFrom:
            - configMapRef:
                name: kafka-consumer.env
          image: kafka-consumer
#          imagePullPolicy: Always
          ports:
            - name: health
              containerPort: 8888
              protocol: TCP
          resources:
            requests:
              memory: 75M
              cpu: 50m
            limits:
              memory: 75M
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /ready
              port: health
            initialDelaySeconds: 2
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: health
