---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-producer
        v: v1
    spec:
      containers:
        - name: producer
          envFrom:
            - configMapRef:
                name: kafka-producer.env
          image: kafka-producer
#          imagePullPolicy: Always
          ports:
            - name: health
              containerPort: 8888
              protocol: TCP
          resources:
            requests:
              memory: 75M
              cpu: 50m
            limits:
              memory: 75M
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /ready
              port: health
            initialDelaySeconds: 2
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: health
